/* ===================================================
 * dtooltip.js v0.5
 * ===================================================
 * Copyright 2012 Kim Lindhardt Madsen
 *
 * Released under the MIT and GPL licenses.
 * ========================================================== */
(function(e){function r(a){return"function"==typeof a?r(a()):a}function s(a,c,g,j,p){var b,d=a[0].ownerDocument;e.dTooltip.dynamicStyle||(b=d.getElementsByTagName("head")[0],d=d.createElement("style"),d.type="text/css",b.appendChild(d),e.dTooltip.dynamicStyle=d);b=e.dTooltip.dynamicStyle;var k;b.styleSheet&&(k=b.styleSheet);b.sheet&&(k=b.sheet);var m;if(180===c)c="Top",b="Bottom",d="Right",m=a.width()/2;else if(90===c)c="Left",b="Right",d="Bottom",m=a.height()/2;else if(0===c||360===c)c="Bottom",
b="Top",d="Left",m=a.width()/2;else if(270===c)c="Right",b="Left",d="Top",m=a.height()/2;else throw"angle is not supported";a.css("-webkit-touch-callout","none").css("-webkit-user-select","none").css("-khtml-user-select","none").css("-moz-user-select","none").css("-ms-user-select","none").css("user-select","none");var l,q,n,f;if(p){l=a[0].ownerDocument;var h=e(l.createElement("div"));h.addClass(j).addClass("hover");e(l.body).append(h);l=parseInt(h.css("border"+c+"Width"),10);q=h.css("border"+c+"Color");
n=h.css("border"+c+"Style");f=h.css("backgroundColor");h.remove()}else l=parseInt(a.css("border"+c+"Width"),10),q=a.css("border"+c+"Color"),n=a.css("border"+c+"Style"),f=a.css("backgroundColor");l||(l=0,q=f);if(!n||"none"===n)n="solid";a="#"+a.attr("id");h=a+"."+j;p&&(h+=".hover");(this.afterRule=t(k,h+":after"))&&u(this.afterRule.style,c,b,d,g-l,n,g-l,f,m);j=a+"."+j;p&&(j+=".hover");(this.beforeRule=t(k,j+":before"))&&u(this.beforeRule.style,c,b,d,g,n,g,q,m-l);return[this.beforeRule,this.afterRule]}
function u(a,c,g,j,e,b,d,k,m){a.borderWidth=e+"px";a.borderColor="transparent";a.borderStyle=b;a["border"+c+"Width"]="0px";a["border"+g+"Width"]=d+"px";a["border"+g+"Color"]=k;a.position="absolute";a.height="0";a.width="0";a[g.toLowerCase()]="100%";a[j.toLowerCase()]=m+"px";a.display="inline-block";try{a.content='""'}catch(l){}}function t(a,c){var g=v(a,c);if(g)return g;a.addRule?a.addRule(c):a.insertRule&&a.insertRule(c+"{}",0);return v(a,c)}function v(a,c){var g=a.cssRules?a.cssRules:a.rules;if(g)for(var j=
0;j<g.length;j++){var e=g[j];if(e.selectorText&&e.selectorText.toLowerCase().replace(/:/g,"")==c.toLowerCase().replace(/:/g,""))return e}return null}e.extend({dTooltip:{version:0.5,defaults:{angle:180,cssClass:"dtooltip",spacing:5,offset:{top:0,left:0},content:"<p>Insert html</p>",showEvent:"mouseenter",hideEvent:"mouseleave",showDelay:0,hideDelay:0}}});e.fn.extend({dTooltip:function(a){function c(){var a=$(p),c=b.spacing;b.arrowSize&&(c+=b.arrowSize);var f=d,h=b.angle,g=b.offset;if(360<h||0>h)throw"You have misconfigured the tooltip - please choose from an angle between 0-360 degrees for the object: #"+
a.attr("id");var e=a.offset(),j,k,l;j=a.width()+(a.outerWidth()-a.width());a=a.height()+(a.outerWidth()-a.width());k=f.width()+(f.outerWidth()-f.width());l=f.height()+(f.outerWidth()-f.width());f=[];if(0===h||360===h)f[0]=e.left+Math.round(j/2)-Math.round(k/2),f[1]=e.top-(l+c);else if(90===h)f[0]=e.left+j+c,f[1]=e.top+Math.round(a/2-l/2);else if(180===h)f[0]=e.left+Math.round(j/2)-Math.round(k/2),f[1]=e.top+a+c;else if(270===h)f[0]=e.left-(k+c),f[1]=e.top+Math.round(a/2-l/2);else throw"angle is not at this time";
f[0]+=g.left;f[1]+=g.top;h=d;c=f[0];g=f[1];h.css("position","absolute");h.css("top",g);h.css("left",c)}function g(){c();b.show?b.show.call(k,d):d.fadeIn(200)}function j(){b.remove?b.hide.call(k,d):d.fadeOut(200)}var p=this,b=e.extend({},e.dTooltip.defaults,a);a="dTooltip_"+this.attr("id");var d=e(document.createElement("div")).addClass(b.cssClass).attr("id",a).css("display","none"),k={},m=!1,l=!1;b.showEvent&&this.bind(b.showEvent,function(){l=!1;m=!0;window.setTimeout(function(){l||g()},b.showDelay)});
b.hideEvent&&this.bind(b.hideEvent,function(){l=!0;m=!1;window.setTimeout(function(){m||j()},b.hideDelay)});this.hover(function(){$(d).addClass("hover")},function(){$(d).removeClass("hover")});d.html(r(b.content));e(document.body).append(d);b.arrowSize&&(s(d,b.angle,b.arrowSize,b.cssClass),s(d,b.angle,b.arrowSize,b.cssClass,!0));k.element=d;k.reposition=c;k.reveal=g;k.hide=j;k.remove=function(){d.remove()};k.setHtml=function(a){d.html(r(a))};return k}})})(jQuery);